# Generated by Django 5.0 on 2024-04-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('dimension', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=500)),
                ('possession', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500)),
                ('property_image1', models.FileField(upload_to='pictures')),
                ('property_image2', models.FileField(upload_to='pictures')),
                ('property_image3', models.FileField(upload_to='pictures')),
                ('property_image4', models.FileField(upload_to='pictures')),
                ('property_image5', models.FileField(upload_to='pictures')),
                ('property_image6', models.FileField(upload_to='pictures')),
                ('property_image7', models.FileField(upload_to='pictures')),
                ('property_image8', models.FileField(upload_to='pictures')),
            ],
        ),
    ]
