# Generated by Django 5.0 on 2024-04-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srkapp', '0002_alter_product_tbl_property_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tbl',
            name='property_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
